### ISSUE TITLE
How to extend the program to 16-bit tif pictures?

### ISSUE THREAD

**Issue by LiangJunhao-THU** [bmmi/denoising-fluorescence#2]
Hello, I'm sorry to bother you.

But as far as I know, most images in the field of biomedicine are 16-bit tif images.

I tried some 16-bit images in the program, but because the PIL package cannot read 16-bit tif images, the program cannot run. After that, I converted the tif file into a 16-bit png format and sent it to test_example.py for testing. At this time, the image can be read, but the results are blank images. Then I converted the image to 8-bit png format, this time the program successfully completed the denoising task.
![n2n_noise1_1_test19_idx0_denoised](https://user-images.githubusercontent.com/41545346/71571028-3910d980-2b13-11ea-809d-492ad0202a39.png)
But 8-bit is missing a lot of information compared to 16-bit. So I would like to ask how to make this program run smoothly on 16-bit image set? And how to call the program when inputting 1024 * 1024 images?

thank you very much!

**Comment by yzhang34** [comment]
Hi Alan,

Thank you for raising this question.

We chose 8-bit png images for the following reasons:
(1) While some microscopes, as you mentioned, generate 16-bit images, some other microscopes we used only output 12-bit images. Since 12-bit is not a common bit-depth, we decided to scale all the images down to 8-bit, which is a commonly used format.
(2) Almost all the state-of-the-art denoising tools use 8-bit images.

We, however, are aware of this drawback. Therefore, we are building a new ImageJ-based tool that can take 16-bit images as input. 

On the other hand, to use image sizes other than 512x512, you need to crop the image down to multiple 512x512 patches, denoise each patch with the network, and then stitch the denoised patches together. The new tool that we are developing can automatically do this.

I hope this answers your questions.

**Comment by LiangJunhao-THU** [comment]
Thank you very much for your reply.

I also want to understand why inputting a 16-bit png image results in a blank image, while inputting an 8-bit png image can be denoised normally? Except for PIL.imread (), which functions in the current program limit the denoising of 16-bit png images? And why does 16-bit generate a blank picture?

I am looking forward to using your new tool! Thank you again for your reply.

**Comment by yzhang34** [comment]
Hi Alan,

When you input a 16-bit image to the program, the pixel value should have a range between 0 to 65535, while for an 8-bit image, the range is between 0 to 255. The neural network was trained with 8-bit images only, so it only works for input images with a pixel value between 0 to 255. When you input a 16-bit image, most of the pixel values are larger than 255, so it is likely that the network saturates and gives you a blank picture.

Here is something you could try with the 16-bit image: before you input the image to the model, use some tools like ImageJ or Matlab to linearly scale the pixel value of the 16-bit image from [0, 65535] to [0, 255]. Yes, you will lose your precision, but you may not get a blank picture this time.

Alternatively, you can try making this image to a single (32-bit) or float (64-bit) format. Then, when you scale the pixel values to [0, 255], you will not lose the precision. For example, a 3000 (16-bit) becomes 3000/65535*255=11.67.

**Comment by LiangJunhao-THU** [comment]
Thank you for your suggestions. I will try the method soon.
Best wishes!

**Comment by Nano-RK** [comment]
Hello，sorry to bother you.

I'm afraid i meet the same problem.  So did the above method solve the problem？I hope to give some advice sincerely！

Also，I am looking forward to using the new tool，hope the author can see this reply.

Thank you vary much!

**Comment by yzhang34** [comment]
> Hello，sorry to bother you.
> 
> I'm afraid i meet the same problem. So did the above method solve the problem？I hope to give some advice sincerely！
> 
> Also，I am looking forward to using the new tool，hope the author can see this reply.
> 
> Thank you vary much!

Yes, please follow the instructions in my answer above.
Thanks.
