### ISSUE TITLE
Why there is a big difference between the brightness of concocal BPAE obtained by network training and ground truth 

### ISSUE THREAD

**Issue by cg-6x** [bmmi/denoising-fluorescence#3]
Hello, I'm sorry to bother you.

I retrained the DnCNN and Noise2Noise networks, tested the model, and got the denoising image in the test mix data set. I combined the images of three channels of focal BPAE into color images, but found that the resulting images are very different from the ground truth (color).

![Confocal_BPAE_3_gt](https://user-images.githubusercontent.com/58495645/78134331-8b370300-7452-11ea-8521-d956b801821f.png)
![n2n-Confocal_BPAE_3](https://user-images.githubusercontent.com/58495645/78134371-9f7b0000-7452-11ea-802c-f38474e2f481.png)

The gray images obtained from network training are all three-channel, while the gray images in the ground truth are single channel. I guess it may be related to this, but no solution has been found. How to deal with this?

**Comment by yzhang34** [comment]
Hello,

Yes, what you are seeing is normal. 

It seems to me that the resulting images of your networks are successfully denoised. You may compare each individual gray-scale channel to verify that. Alternatively, you may calculate the PSNR or SSIM between these two images.

Regarding your question, it is simply caused by the different dynamic ranges (i.e., contrast & brightness) your computer used to display these images. To change the dynamic ranges, you can export these images, open them in ImageJ, and adjust the brightness & contrast for each channel. For more details, please check this link: https://imagej.net/Brightness_and_Contrast

I'm sure that, after adjustment, the two images will be very similar.

Best,
Yide

**Comment by cg-6x** [comment]
Thank you for your suggestions. I will try the method soon.
Best wishes!
